name: Run Laravel Migrations on Push

on:
  push:
    branches:
      - main  # Change to 'master' or your branch if different

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Change version if your Laravel uses a different one

      # Step 3: Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 4: Copy .env variables for Artisan
      - name: Setup environment variables
        run: |
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=base64:SomeRandomKey1234567890=" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      # Step 5: Generate app key (required for Laravel)
      - name: Generate APP Key
        run: php artisan key:generate

      # Step 6: Run migrations
      - name: Run Laravel Migrations
        run: php artisan migrate --force
